theme: hacker-file


SILENCE IS THE MISSION

Hello, I'm the Master Of Silence

And this is my GitHub pages.


I'll post project updates, random thoughts and overall the hardness of coding.

So have fun here


August 27

Ugh. I'm so bored with classes. 

Its like sitting in an endless torture chamber!

Especially on a friday. Nothing to do but deliver a package to my friend

https://www.images.app.goo.gl/vsyN7pd4xEyKYYHG7

As they say, A picture says a thousand words!

(CANT FIGURE OUT HOW TO ADD A LINK, WORKING ON IT!)
