theme: hacker-file


SILENCE IS THE MISSION

Hello, I'm the Master Of Silence

And this is my GitHub pages.


I'll post project updates, random thoughts and overall the hardness of coding.

So have fun here
